// Code generated by hertz generator.

package user

import (
	"context"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/example/hertz-kitex-demo/hertz_service/biz/client"
	"github.com/example/hertz-kitex-demo/hertz_service/biz/model/user"
	rpcuser "github.com/example/hertz-kitex-demo/kitex_gen/user"
)

// CreateUser 创建用户
// @router /api/v1/users [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var req user.CreateUserRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{
			"code":    400,
			"message": "invalid request: " + err.Error(),
		})
		return
	}

	// 调用 RPC 服务
	rpcReq := &rpcuser.CreateUserRequest{
		Username: req.Username,
		Email:    req.Email,
		Phone:    req.Phone,
	}

	rpcResp, err := client.GetUserClient().CreateUser(ctx, rpcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{
			"code":    500,
			"message": "rpc call failed: " + err.Error(),
		})
		return
	}

	// 构造响应
	resp := &user.CreateUserResponse{
		Code:    rpcResp.Code,
		Message: rpcResp.Message,
	}

	if rpcResp.User != nil {
		resp.User = &user.User{
			ID:        rpcResp.User.Id,
			Username:  rpcResp.User.Username,
			Email:     rpcResp.User.Email,
			Phone:     rpcResp.User.Phone,
			CreatedAt: rpcResp.User.CreatedAt,
			UpdatedAt: rpcResp.User.UpdatedAt,
		}
	}

	if resp.Code == 0 {
		c.JSON(consts.StatusOK, resp)
	} else {
		c.JSON(consts.StatusBadRequest, resp)
	}
}

// GetUser 获取用户
// @router /api/v1/users/:id [GET]
func GetUser(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Param("id")
	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{
			"code":    400,
			"message": "invalid user_id",
		})
		return
	}

	// 调用 RPC 服务
	rpcReq := &rpcuser.GetUserRequest{
		UserId: userID,
	}

	rpcResp, err := client.GetUserClient().GetUser(ctx, rpcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{
			"code":    500,
			"message": "rpc call failed: " + err.Error(),
		})
		return
	}

	// 构造响应
	resp := &user.GetUserResponse{
		Code:    rpcResp.Code,
		Message: rpcResp.Message,
	}

	if rpcResp.User != nil {
		resp.User = &user.User{
			ID:        rpcResp.User.Id,
			Username:  rpcResp.User.Username,
			Email:     rpcResp.User.Email,
			Phone:     rpcResp.User.Phone,
			CreatedAt: rpcResp.User.CreatedAt,
			UpdatedAt: rpcResp.User.UpdatedAt,
		}
	}

	if resp.Code == 0 {
		c.JSON(consts.StatusOK, resp)
	} else if resp.Code == 404 {
		c.JSON(consts.StatusNotFound, resp)
	} else {
		c.JSON(consts.StatusInternalServerError, resp)
	}
}

// UpdateUser 更新用户
// @router /api/v1/users/:id [PUT]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Param("id")
	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{
			"code":    400,
			"message": "invalid user_id",
		})
		return
	}

	var req user.UpdateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{
			"code":    400,
			"message": "invalid request: " + err.Error(),
		})
		return
	}

	// 调用 RPC 服务
	rpcReq := &rpcuser.UpdateUserRequest{
		UserId:   userID,
		Username: req.Username,
		Email:    req.Email,
		Phone:    req.Phone,
	}

	rpcResp, err := client.GetUserClient().UpdateUser(ctx, rpcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{
			"code":    500,
			"message": "rpc call failed: " + err.Error(),
		})
		return
	}

	// 构造响应
	resp := &user.UpdateUserResponse{
		Code:    rpcResp.Code,
		Message: rpcResp.Message,
	}

	if resp.Code == 0 {
		c.JSON(consts.StatusOK, resp)
	} else if resp.Code == 404 {
		c.JSON(consts.StatusNotFound, resp)
	} else {
		c.JSON(consts.StatusBadRequest, resp)
	}
}

// DeleteUser 删除用户
// @router /api/v1/users/:id [DELETE]
func DeleteUser(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Param("id")
	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{
			"code":    400,
			"message": "invalid user_id",
		})
		return
	}

	// 调用 RPC 服务
	rpcReq := &rpcuser.DeleteUserRequest{
		UserId: userID,
	}

	rpcResp, err := client.GetUserClient().DeleteUser(ctx, rpcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{
			"code":    500,
			"message": "rpc call failed: " + err.Error(),
		})
		return
	}

	// 构造响应
	resp := &user.DeleteUserResponse{
		Code:    rpcResp.Code,
		Message: rpcResp.Message,
	}

	if resp.Code == 0 {
		c.JSON(consts.StatusOK, resp)
	} else if resp.Code == 404 {
		c.JSON(consts.StatusNotFound, resp)
	} else {
		c.JSON(consts.StatusInternalServerError, resp)
	}
}

// ListUsers 获取用户列表
// @router /api/v1/users [GET]
func ListUsers(ctx context.Context, c *app.RequestContext) {
	pageStr := c.DefaultQuery("page", "1")
	pageSizeStr := c.DefaultQuery("page_size", "10")

	page, err := strconv.Atoi(pageStr)
	if err != nil || page < 1 {
		page = 1
	}

	pageSize, err := strconv.Atoi(pageSizeStr)
	if err != nil || pageSize < 1 || pageSize > 100 {
		pageSize = 10
	}

	// 调用 RPC 服务
	rpcReq := &rpcuser.ListUsersRequest{
		Page:     int32(page),
		PageSize: int32(pageSize),
	}

	rpcResp, err := client.GetUserClient().ListUsers(ctx, rpcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{
			"code":    500,
			"message": "rpc call failed: " + err.Error(),
		})
		return
	}

	// 构造响应
	resp := &user.ListUsersResponse{
		Code:    rpcResp.Code,
		Message: rpcResp.Message,
	}

	users := make([]*user.User, 0, len(rpcResp.Users))
	for _, u := range rpcResp.Users {
		users = append(users, &user.User{
			ID:        u.Id,
			Username:  u.Username,
			Email:     u.Email,
			Phone:     u.Phone,
			CreatedAt: u.CreatedAt,
			UpdatedAt: u.UpdatedAt,
		})
	}

	resp.Users = users
	resp.Total = rpcResp.Total

	c.JSON(consts.StatusOK, resp)
}
