// Code generated by hertz generator.

package main

import (
	"context"
	"fmt"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/example/hertz-kitex-demo/hertz_service/biz/client"
	"github.com/example/hertz-kitex-demo/hertz_service/biz/config"
	"github.com/example/hertz-kitex-demo/hertz_service/biz/handler/user"
)

func main() {
	// 加载配置
	cfg := config.GetConfig()

	// 初始化 RPC 客户端
	if err := client.InitUserClient(cfg); err != nil {
		log.Fatalf("Failed to initialize RPC client: %v", err)
	}

	// 创建 Hertz HTTP 服务器
	h := server.Default(
		server.WithHostPorts(fmt.Sprintf("%s:%s", cfg.HTTP.Host, cfg.HTTP.Port)),
	)

	// 注册路由
	registerRoutes(h)

	log.Printf("Hertz HTTP Server starting at %s:%s", cfg.HTTP.Host, cfg.HTTP.Port)
	h.Spin()
}

func registerRoutes(h *server.Hertz) {
	// 健康检查
	h.GET("/ping", func(ctx context.Context, c *app.RequestContext) {
		c.JSON(consts.StatusOK, utils.H{
			"message": "pong",
		})
	})

	// API 路由组
	api := h.Group("/api/v1")
	{
		// 用户相关路由
		users := api.Group("/users")
		{
			users.POST("", user.CreateUser)       // 创建用户
			users.GET("/:id", user.GetUser)       // 获取用户
			users.PUT("/:id", user.UpdateUser)    // 更新用户
			users.DELETE("/:id", user.DeleteUser) // 删除用户
			users.GET("", user.ListUsers)         // 获取用户列表
		}
	}
}
