// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type User struct {
	ID        int64  `thrift:"ID,1" frugal:"1,default,i64" json:"id"`
	Username  string `thrift:"Username,2" frugal:"2,default,string" json:"username"`
	Email     string `thrift:"Email,3" frugal:"3,default,string" json:"email"`
	Phone     string `thrift:"Phone,4" frugal:"4,default,string" json:"phone"`
	CreatedAt int64  `thrift:"CreatedAt,5" frugal:"5,default,i64" json:"created_at"`
	UpdatedAt int64  `thrift:"UpdatedAt,6" frugal:"6,default,i64" json:"updated_at"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetID() (v int64) {
	return p.ID
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetPhone() (v string) {
	return p.Phone
}

func (p *User) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *User) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *User) SetID(val int64) {
	p.ID = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetPhone(val string) {
	p.Phone = val
}
func (p *User) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *User) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "ID",
	2: "Username",
	3: "Email",
	4: "Phone",
	5: "CreatedAt",
	6: "UpdatedAt",
}

type CreateUserRequest struct {
	Username string  `thrift:"Username,1,required" frugal:"1,required,string" json:"username" form:"username" vd:"len($) > 0 && len($) <= 64"`
	Email    string  `thrift:"Email,2,required" frugal:"2,required,string" json:"email" form:"email" vd:"len($) > 0 && len($) <= 128"`
	Phone    *string `thrift:"Phone,3,optional" frugal:"3,optional,string" json:"phone,omitempty" form:"phone" vd:"len($) == 0 || len($) == 11"`
}

func NewCreateUserRequest() *CreateUserRequest {
	return &CreateUserRequest{}
}

func (p *CreateUserRequest) InitDefault() {
}

func (p *CreateUserRequest) GetUsername() (v string) {
	return p.Username
}

func (p *CreateUserRequest) GetEmail() (v string) {
	return p.Email
}

var CreateUserRequest_Phone_DEFAULT string

func (p *CreateUserRequest) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return CreateUserRequest_Phone_DEFAULT
	}
	return *p.Phone
}
func (p *CreateUserRequest) SetUsername(val string) {
	p.Username = val
}
func (p *CreateUserRequest) SetEmail(val string) {
	p.Email = val
}
func (p *CreateUserRequest) SetPhone(val *string) {
	p.Phone = val
}

func (p *CreateUserRequest) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *CreateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserRequest(%+v)", *p)
}

var fieldIDToName_CreateUserRequest = map[int16]string{
	1: "Username",
	2: "Email",
	3: "Phone",
}

type CreateUserResponse struct {
	Code    int32  `thrift:"Code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"Message,2" frugal:"2,default,string" json:"message"`
	User    *User  `thrift:"User,3,optional" frugal:"3,optional,User" json:"user,omitempty"`
}

func NewCreateUserResponse() *CreateUserResponse {
	return &CreateUserResponse{}
}

func (p *CreateUserResponse) InitDefault() {
}

func (p *CreateUserResponse) GetCode() (v int32) {
	return p.Code
}

func (p *CreateUserResponse) GetMessage() (v string) {
	return p.Message
}

var CreateUserResponse_User_DEFAULT *User

func (p *CreateUserResponse) GetUser() (v *User) {
	if !p.IsSetUser() {
		return CreateUserResponse_User_DEFAULT
	}
	return p.User
}
func (p *CreateUserResponse) SetCode(val int32) {
	p.Code = val
}
func (p *CreateUserResponse) SetMessage(val string) {
	p.Message = val
}
func (p *CreateUserResponse) SetUser(val *User) {
	p.User = val
}

func (p *CreateUserResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *CreateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserResponse(%+v)", *p)
}

var fieldIDToName_CreateUserResponse = map[int16]string{
	1: "Code",
	2: "Message",
	3: "User",
}

type GetUserRequest struct {
	UserID int64 `thrift:"UserID,1,required" frugal:"1,required,i64" json:"user_id" path:"id" vd:"$ > 0"`
}

func NewGetUserRequest() *GetUserRequest {
	return &GetUserRequest{}
}

func (p *GetUserRequest) InitDefault() {
}

func (p *GetUserRequest) GetUserID() (v int64) {
	return p.UserID
}
func (p *GetUserRequest) SetUserID(val int64) {
	p.UserID = val
}

func (p *GetUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRequest(%+v)", *p)
}

var fieldIDToName_GetUserRequest = map[int16]string{
	1: "UserID",
}

type GetUserResponse struct {
	Code    int32  `thrift:"Code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"Message,2" frugal:"2,default,string" json:"message"`
	User    *User  `thrift:"User,3,optional" frugal:"3,optional,User" json:"user,omitempty"`
}

func NewGetUserResponse() *GetUserResponse {
	return &GetUserResponse{}
}

func (p *GetUserResponse) InitDefault() {
}

func (p *GetUserResponse) GetCode() (v int32) {
	return p.Code
}

func (p *GetUserResponse) GetMessage() (v string) {
	return p.Message
}

var GetUserResponse_User_DEFAULT *User

func (p *GetUserResponse) GetUser() (v *User) {
	if !p.IsSetUser() {
		return GetUserResponse_User_DEFAULT
	}
	return p.User
}
func (p *GetUserResponse) SetCode(val int32) {
	p.Code = val
}
func (p *GetUserResponse) SetMessage(val string) {
	p.Message = val
}
func (p *GetUserResponse) SetUser(val *User) {
	p.User = val
}

func (p *GetUserResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResponse(%+v)", *p)
}

var fieldIDToName_GetUserResponse = map[int16]string{
	1: "Code",
	2: "Message",
	3: "User",
}

type UpdateUserRequest struct {
	UserID   int64   `thrift:"UserID,1,required" frugal:"1,required,i64" json:"user_id" path:"id" vd:"$ > 0"`
	Username *string `thrift:"Username,2,optional" frugal:"2,optional,string" json:"username,omitempty" form:"username" vd:"len($) == 0 || len($) <= 64"`
	Email    *string `thrift:"Email,3,optional" frugal:"3,optional,string" json:"email,omitempty" form:"email" vd:"len($) == 0 || len($) <= 128"`
	Phone    *string `thrift:"Phone,4,optional" frugal:"4,optional,string" json:"phone,omitempty" form:"phone" vd:"len($) == 0 || len($) == 11"`
}

func NewUpdateUserRequest() *UpdateUserRequest {
	return &UpdateUserRequest{}
}

func (p *UpdateUserRequest) InitDefault() {
}

func (p *UpdateUserRequest) GetUserID() (v int64) {
	return p.UserID
}

var UpdateUserRequest_Username_DEFAULT string

func (p *UpdateUserRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return UpdateUserRequest_Username_DEFAULT
	}
	return *p.Username
}

var UpdateUserRequest_Email_DEFAULT string

func (p *UpdateUserRequest) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return UpdateUserRequest_Email_DEFAULT
	}
	return *p.Email
}

var UpdateUserRequest_Phone_DEFAULT string

func (p *UpdateUserRequest) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return UpdateUserRequest_Phone_DEFAULT
	}
	return *p.Phone
}
func (p *UpdateUserRequest) SetUserID(val int64) {
	p.UserID = val
}
func (p *UpdateUserRequest) SetUsername(val *string) {
	p.Username = val
}
func (p *UpdateUserRequest) SetEmail(val *string) {
	p.Email = val
}
func (p *UpdateUserRequest) SetPhone(val *string) {
	p.Phone = val
}

func (p *UpdateUserRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *UpdateUserRequest) IsSetEmail() bool {
	return p.Email != nil
}

func (p *UpdateUserRequest) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UpdateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserRequest(%+v)", *p)
}

var fieldIDToName_UpdateUserRequest = map[int16]string{
	1: "UserID",
	2: "Username",
	3: "Email",
	4: "Phone",
}

type UpdateUserResponse struct {
	Code    int32  `thrift:"Code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"Message,2" frugal:"2,default,string" json:"message"`
}

func NewUpdateUserResponse() *UpdateUserResponse {
	return &UpdateUserResponse{}
}

func (p *UpdateUserResponse) InitDefault() {
}

func (p *UpdateUserResponse) GetCode() (v int32) {
	return p.Code
}

func (p *UpdateUserResponse) GetMessage() (v string) {
	return p.Message
}
func (p *UpdateUserResponse) SetCode(val int32) {
	p.Code = val
}
func (p *UpdateUserResponse) SetMessage(val string) {
	p.Message = val
}

func (p *UpdateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserResponse(%+v)", *p)
}

var fieldIDToName_UpdateUserResponse = map[int16]string{
	1: "Code",
	2: "Message",
}

type DeleteUserRequest struct {
	UserID int64 `thrift:"UserID,1,required" frugal:"1,required,i64" json:"user_id" path:"id" vd:"$ > 0"`
}

func NewDeleteUserRequest() *DeleteUserRequest {
	return &DeleteUserRequest{}
}

func (p *DeleteUserRequest) InitDefault() {
}

func (p *DeleteUserRequest) GetUserID() (v int64) {
	return p.UserID
}
func (p *DeleteUserRequest) SetUserID(val int64) {
	p.UserID = val
}

func (p *DeleteUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserRequest(%+v)", *p)
}

var fieldIDToName_DeleteUserRequest = map[int16]string{
	1: "UserID",
}

type DeleteUserResponse struct {
	Code    int32  `thrift:"Code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"Message,2" frugal:"2,default,string" json:"message"`
}

func NewDeleteUserResponse() *DeleteUserResponse {
	return &DeleteUserResponse{}
}

func (p *DeleteUserResponse) InitDefault() {
}

func (p *DeleteUserResponse) GetCode() (v int32) {
	return p.Code
}

func (p *DeleteUserResponse) GetMessage() (v string) {
	return p.Message
}
func (p *DeleteUserResponse) SetCode(val int32) {
	p.Code = val
}
func (p *DeleteUserResponse) SetMessage(val string) {
	p.Message = val
}

func (p *DeleteUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserResponse(%+v)", *p)
}

var fieldIDToName_DeleteUserResponse = map[int16]string{
	1: "Code",
	2: "Message",
}

type ListUsersRequest struct {
	Page     int32 `thrift:"Page,1,required" frugal:"1,required,i32" json:"page" form:"page" query:"page" vd:"$ > 0"`
	PageSize int32 `thrift:"PageSize,2,required" frugal:"2,required,i32" json:"page_size" form:"page_size" query:"page_size" vd:"$ > 0 && $ <= 100"`
}

func NewListUsersRequest() *ListUsersRequest {
	return &ListUsersRequest{}
}

func (p *ListUsersRequest) InitDefault() {
}

func (p *ListUsersRequest) GetPage() (v int32) {
	return p.Page
}

func (p *ListUsersRequest) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListUsersRequest) SetPage(val int32) {
	p.Page = val
}
func (p *ListUsersRequest) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListUsersRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListUsersRequest(%+v)", *p)
}

var fieldIDToName_ListUsersRequest = map[int16]string{
	1: "Page",
	2: "PageSize",
}

type ListUsersResponse struct {
	Code    int32   `thrift:"Code,1" frugal:"1,default,i32" json:"code"`
	Message string  `thrift:"Message,2" frugal:"2,default,string" json:"message"`
	Users   []*User `thrift:"Users,3" frugal:"3,default,list<User>" json:"users,omitempty"`
	Total   int64   `thrift:"Total,4" frugal:"4,default,i64" json:"total"`
}

func NewListUsersResponse() *ListUsersResponse {
	return &ListUsersResponse{}
}

func (p *ListUsersResponse) InitDefault() {
}

func (p *ListUsersResponse) GetCode() (v int32) {
	return p.Code
}

func (p *ListUsersResponse) GetMessage() (v string) {
	return p.Message
}

func (p *ListUsersResponse) GetUsers() (v []*User) {
	return p.Users
}

func (p *ListUsersResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *ListUsersResponse) SetCode(val int32) {
	p.Code = val
}
func (p *ListUsersResponse) SetMessage(val string) {
	p.Message = val
}
func (p *ListUsersResponse) SetUsers(val []*User) {
	p.Users = val
}
func (p *ListUsersResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *ListUsersResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListUsersResponse(%+v)", *p)
}

var fieldIDToName_ListUsersResponse = map[int16]string{
	1: "Code",
	2: "Message",
	3: "Users",
	4: "Total",
}

type UserService interface {
	CreateUser(ctx context.Context, req *CreateUserRequest) (r *CreateUserResponse, err error)

	GetUser(ctx context.Context, req *GetUserRequest) (r *GetUserResponse, err error)

	UpdateUser(ctx context.Context, req *UpdateUserRequest) (r *UpdateUserResponse, err error)

	DeleteUser(ctx context.Context, req *DeleteUserRequest) (r *DeleteUserResponse, err error)

	ListUsers(ctx context.Context, req *ListUsersRequest) (r *ListUsersResponse, err error)
}

type UserServiceCreateUserArgs struct {
	Req *CreateUserRequest `thrift:"req,1" frugal:"1,default,CreateUserRequest" json:"req"`
}

func NewUserServiceCreateUserArgs() *UserServiceCreateUserArgs {
	return &UserServiceCreateUserArgs{}
}

func (p *UserServiceCreateUserArgs) InitDefault() {
}

var UserServiceCreateUserArgs_Req_DEFAULT *CreateUserRequest

func (p *UserServiceCreateUserArgs) GetReq() (v *CreateUserRequest) {
	if !p.IsSetReq() {
		return UserServiceCreateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateUserArgs) SetReq(val *CreateUserRequest) {
	p.Req = val
}

func (p *UserServiceCreateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateUserResult struct {
	Success *CreateUserResponse `thrift:"success,0,optional" frugal:"0,optional,CreateUserResponse" json:"success,omitempty"`
}

func NewUserServiceCreateUserResult() *UserServiceCreateUserResult {
	return &UserServiceCreateUserResult{}
}

func (p *UserServiceCreateUserResult) InitDefault() {
}

var UserServiceCreateUserResult_Success_DEFAULT *CreateUserResponse

func (p *UserServiceCreateUserResult) GetSuccess() (v *CreateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCreateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateUserResponse)
}

func (p *UserServiceCreateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserArgs struct {
	Req *GetUserRequest `thrift:"req,1" frugal:"1,default,GetUserRequest" json:"req"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Req_DEFAULT *GetUserRequest

func (p *UserServiceGetUserArgs) GetReq() (v *GetUserRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserArgs) SetReq(val *GetUserRequest) {
	p.Req = val
}

func (p *UserServiceGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserResult struct {
	Success *GetUserResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *GetUserResponse

func (p *UserServiceGetUserResult) GetSuccess() (v *GetUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResponse)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserArgs struct {
	Req *UpdateUserRequest `thrift:"req,1" frugal:"1,default,UpdateUserRequest" json:"req"`
}

func NewUserServiceUpdateUserArgs() *UserServiceUpdateUserArgs {
	return &UserServiceUpdateUserArgs{}
}

func (p *UserServiceUpdateUserArgs) InitDefault() {
}

var UserServiceUpdateUserArgs_Req_DEFAULT *UpdateUserRequest

func (p *UserServiceUpdateUserArgs) GetReq() (v *UpdateUserRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserArgs) SetReq(val *UpdateUserRequest) {
	p.Req = val
}

func (p *UserServiceUpdateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserResult struct {
	Success *UpdateUserResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateUserResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateUserResult() *UserServiceUpdateUserResult {
	return &UserServiceUpdateUserResult{}
}

func (p *UserServiceUpdateUserResult) InitDefault() {
}

var UserServiceUpdateUserResult_Success_DEFAULT *UpdateUserResponse

func (p *UserServiceUpdateUserResult) GetSuccess() (v *UpdateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserResponse)
}

func (p *UserServiceUpdateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteUserArgs struct {
	Req *DeleteUserRequest `thrift:"req,1" frugal:"1,default,DeleteUserRequest" json:"req"`
}

func NewUserServiceDeleteUserArgs() *UserServiceDeleteUserArgs {
	return &UserServiceDeleteUserArgs{}
}

func (p *UserServiceDeleteUserArgs) InitDefault() {
}

var UserServiceDeleteUserArgs_Req_DEFAULT *DeleteUserRequest

func (p *UserServiceDeleteUserArgs) GetReq() (v *DeleteUserRequest) {
	if !p.IsSetReq() {
		return UserServiceDeleteUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteUserArgs) SetReq(val *DeleteUserRequest) {
	p.Req = val
}

func (p *UserServiceDeleteUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteUserResult struct {
	Success *DeleteUserResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteUserResponse" json:"success,omitempty"`
}

func NewUserServiceDeleteUserResult() *UserServiceDeleteUserResult {
	return &UserServiceDeleteUserResult{}
}

func (p *UserServiceDeleteUserResult) InitDefault() {
}

var UserServiceDeleteUserResult_Success_DEFAULT *DeleteUserResponse

func (p *UserServiceDeleteUserResult) GetSuccess() (v *DeleteUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteUserResponse)
}

func (p *UserServiceDeleteUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserResult = map[int16]string{
	0: "success",
}

type UserServiceListUsersArgs struct {
	Req *ListUsersRequest `thrift:"req,1" frugal:"1,default,ListUsersRequest" json:"req"`
}

func NewUserServiceListUsersArgs() *UserServiceListUsersArgs {
	return &UserServiceListUsersArgs{}
}

func (p *UserServiceListUsersArgs) InitDefault() {
}

var UserServiceListUsersArgs_Req_DEFAULT *ListUsersRequest

func (p *UserServiceListUsersArgs) GetReq() (v *ListUsersRequest) {
	if !p.IsSetReq() {
		return UserServiceListUsersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceListUsersArgs) SetReq(val *ListUsersRequest) {
	p.Req = val
}

func (p *UserServiceListUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceListUsersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListUsersArgs(%+v)", *p)
}

var fieldIDToName_UserServiceListUsersArgs = map[int16]string{
	1: "req",
}

type UserServiceListUsersResult struct {
	Success *ListUsersResponse `thrift:"success,0,optional" frugal:"0,optional,ListUsersResponse" json:"success,omitempty"`
}

func NewUserServiceListUsersResult() *UserServiceListUsersResult {
	return &UserServiceListUsersResult{}
}

func (p *UserServiceListUsersResult) InitDefault() {
}

var UserServiceListUsersResult_Success_DEFAULT *ListUsersResponse

func (p *UserServiceListUsersResult) GetSuccess() (v *ListUsersResponse) {
	if !p.IsSetSuccess() {
		return UserServiceListUsersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListUsersResponse)
}

func (p *UserServiceListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceListUsersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListUsersResult(%+v)", *p)
}

var fieldIDToName_UserServiceListUsersResult = map[int16]string{
	0: "success",
}
